### ISSUE TITLE
Game Modes

### ISSUE THREAD

**Issue by F0RIS** [proxiemind/MultiOgar-Edited#1]
Hi! Thanks for working on gamemodes! but may I ask, when u planning finish it? And may be u can suggest where to get other game modes for MultiOgar?

**Comment by proxiemind** [comment]
@F0RIS Well, for now I'm stopping development. And I have no idea from where you can loot more modes, however you can try to navi thru MO-E forks for searching more: https://github.com/Megabyte918/MultiOgar-Edited/network
