### ISSUE TITLE
Gamemode duel

### ISSUE THREAD

**Issue by gyeyoqu** [proxiemind/MultiOgar-Edited#2]
Hello,

You can do duel 2 vs 2 like gotaio?

**Comment by proxiemind** [comment]
Hey @gyeyoqu 

Not yet, however I have intention to prepare such scenario, so 2v2, 3v3, 2v2v2 - generally N[vN]. Both random and planned (which for me make sense to open such possibility as Match Maker in Cigar client for instance), Party/Team Mode + Classic/Experimental mechanics.

Not sure when I will have time for it tho.
